name: Create Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version tag (e.g., v1.0.0)'
        required: true
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Build project
      run: npm run build

      
    - name: Get version from manifest
      id: version
      run: |
        VERSION=$(grep -oP '<Extension Id="typer".*?Version="\K[^"]+' CSXS/manifest.xml || echo "unknown")

        if [ "$VERSION" = "unknown" ]; then
          echo "error: version not found in manifest"
          exit 1
        fi

        echo "version=$VERSION" >> $GITHUB_OUTPUT
      
    - name: Create ZIP artifact
      run: |
        chmod +x ./build_script.sh
        ./build_script.sh

    - name: Check if ZIP exists
      run: |
          if [ ! -f "dist/typertools-${{ steps.version.outputs.version }}.zip" ]; then
            echo "error: zip file wasn't found"
            ls dist/ 
            exit 1
          fi

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v${{ steps.version.outputs.version }}
        name: TyperTools v${{ steps.version.outputs.version }}
        body: Automatic release 
        files: dist/typertools-${{ steps.version.outputs.version }}.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}