name: Create Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version tag (e.g., v1.0.0)'
        required: true
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install

    - name: Build project
      run: npm run build

    - name: Create ZIP artifact
      run: |
        chmod +x ./build_script.sh
        ./build_script.sh

    - name: Get version from manifest
      id: version
      run: |
        VERSION=$(grep -oP '<Extension Id="typer".*?Version="\K[^"]+' CSXS/manifest.xml || echo "unknown")
        echo "version=$VERSION" >> $GITHUB_OUTPUT

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v${{ steps.version.outputs.version }}-$(date +'%Y%m%d%H%M%S')
        name: TyperTools v${{ steps.version.outputs.version }} ($(date +'%Y-%m-%d'))
        body: Automatic release created on $(date +'%Y-%m-%d %H:%M:%S')
        files: dist/typertools-${{ steps.version.outputs.version }}.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}